import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import { Providers } from "@/components/providers";
import { auth, signOut } from "auth";
import NavbarNextUI from "@/components/NavBarNextUI";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const session = await auth()

  return (
    <html lang="en" >
      <body className={cn('w-screen h-screen flex flex-col  relative ',)}>
       <Providers>
       <NavbarNextUI session={session}  />
        {children}
       </Providers>
       </body>
    </html>
  );
}
